services:
  db:
    image: mysql:8.0
    container_name: inventario-db-1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_ventas
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - backend  

  app:
    build: .
    container_name: inventario-app-1
    depends_on:
      - db
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    networks:
      - backend

networks:
  backend:

volumes:
  db_data: